#generated by Gemini
import struct

def generate_hex_file(filename, total_bytes):
    word_size = 4  # 4 bytes per word
    num_words = total_bytes // word_size
    
    # 'w' mode creates the file if it doesn't exist and overwrites if it does
    with open(filename, 'w') as f:
        for i in range(num_words):
            # Pack the integer into 4 bytes (Big Endian)
            # Example: 1 becomes b'\x00\x00\x00\x01'
            byte_data = struct.pack('>I', i)
            
            # Write two hex characters per line (1 byte per line)
            # Total 4 lines per word
            for byte in byte_data:
                f.write(f"{byte:02X}\n")

if __name__ == "__main__":
    target_file = "output.hex"
    byte_count = 20000
    generate_hex_file(target_file, byte_count)
    print(f"File '{target_file}' generated with {byte_count} bytes.")