#generated by Gemini
import argparse
import sys


def hex_bytes_to_c_array(input_file_path, output_file_path):
    try:
        bytes_list = []

        # Read lines sequentially and stop at a single '0'
        with open(input_file_path, "r") as f:
            for line in f:
                cleaned_line = line.strip()
                if not cleaned_line:
                    continue  # Skip accidental empty lines

                # Check if the line is exactly a single '0'
                if cleaned_line == "0":
                    break

                bytes_list.append(cleaned_line)

        if not bytes_list:
            print(
                f"Warning: No valid bytes were processed from '{input_file_path}'."
            )
            return

        # Convert to 32-bit words (4 bytes per word)
        words = []
        for i in range(0, len(bytes_list), 4):
            chunk = bytes_list[i : i + 4]

            # Pad with "00" if the last chunk has fewer than 4 bytes
            while len(chunk) < 4:
                chunk.append("00")

            # Combine the 4 bytes into a single 32-bit hex string
            word = "".join(chunk)
            words.append(f"    0x{word}")

        # Write the formatted C code to the output file
        with open(output_file_path, "w") as f:
            f.write("#include <stdint.h>\n")
            f.write("volatile static const uint32_t bitstream[] = {\n")
            f.write(",\n".join(words))
            f.write("\n};\n")

        print(
            f"Success: Processed {len(bytes_list)} bytes before hit stop condition."
        )
        print(f"Output saved to: {output_file_path}")

    except FileNotFoundError:
        print(
            f"Error: The file '{input_file_path}' could not be found.",
            file=sys.stderr,
        )
    except Exception as e:
        print(f"An error occurred: {e}", file=sys.stderr)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert a list of raw hex bytes into a C uint32_t array, stopping at a single '0'."
    )
    parser.add_argument(
        "input_file", help="Path to the input text file containing hex bytes."
    )
    parser.add_argument(
        "output_file", help="Path where the output C header file will be saved."
    )

    args = parser.parse_args()
    hex_bytes_to_c_array(args.input_file, args.output_file)